[package]
name = "take-note"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ratatui = "0.29.0"
firebase-rs = "2.0.5"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1.21.2", features = ["full"]}
